name: GameObject.mod
version: '${project.version}'
main: de.luap42.mc.gameobjectmod.GameObjectMod
api-version: '1.21.4'

commands:
  go-lock:
    description: Locks the currently held item stack with a secret key so that only items locked with that key stack.
    usage: /go-lock <key>
  go-unlock:
    description: Unlocks the currently held item stack if the secret key is provided.
    usage: /go-unlock <key>
  go-lore:
    description: Adds/replaces lore on the currently held item stack.
    usage: /go-lore <text>
  go-format:
    description: Allows modifying formatting options for the name of the currently held item stack
    usage: /go-format clear|{bold,italic,yellow,red,pink,purple,blue,aqua,green,darkgreen,white,gray|grey,black}*
  go-custommodel:
    description: Set or clear a custom model data ID
    usage: /go-custommodel clear|<id>
  go-glint:
    description: Override the enchantment glint to always be shown (yes), never be shown (no), or remove override (auto, default)
    usage: /go-glint yes|no|auto
  go-itemmodel:
    description: Set the item_model field of the item to the item model of another item
    usage: /go-model clear|<namespace>:<id>
  go-save:
    description: Saves the GameObject information of the currently held item stack for later /go-apply under your user account
    usage: /go-save <name> [<secretKey>]
  go-apply:
    description: Attempts to apply the GameObject information saved under <name> to the currently held item stack, provided the item name is set correctly
    usage: /go-apply <name>