name: GameObject.mod
version: '${project.version}'
main: de.luap42.mc.gameobjectmod.GameObjectMod
api-version: '1.20'

commands:
  go-lock:
    description: Locks the currently held item stack with a secret key so that only items locked with that key stack.
    usage: /go-lock <key>
    permission: gameobjectmod.lock
  go-unlock:
    description: Unlocks the currently held item stack if the secret key is provided.
    usage: /go-unlock <key>
    permission: gameobjectmod.lock